### ISSUE TITLE
yarn && yarn start  doesn't work. 

### ISSUE THREAD

**Issue by codessi** [satansdeer/minecraft-react#20]
yarn && yarn start  doesn't work. 

I am at new in programming.   when I  yarn && yarn start  after downloading 

first this message,
```
Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db`
```
then,

Failed to compile.

```
./node_modules/use-cannon/dist/index-a727eaf5.js
Attempted import error: 'Geometry' is not exported from 'three' (imported as 'm').

```
I google the error message.  I tried to change the npm version  dependencies and peer deps. 
I thought I should ask about this issue before I move on. 

thank you  for taking time to reading this..

Johan

**Comment by ysuzuki19** [comment]
Hi, @codessi 
I resolved new dependencies in my fork.
Can you work this?
Please try if you like.

Thanks! ( ^ _ ^ )

**Comment by ysuzuki19** [comment]
@codessi 
or please rewrite `"three": "0.125.0"` to `"three": "0.125.1"` in `package.json` and `yarn && yarn start`.
it is changed [this commit](https://github.com/satansdeer/minecraft-react/commit/2380d95a3accd23c2a28418b3a98f4c19e4bd1d6#) by [dependabot](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates)
