### ISSUE TITLE
Project Question

### ISSUE THREAD

**Issue by mmnavarr** [satansdeer/minecraft-react#4]
Is this a repository creating Minecraft in React using react-three-fiber?

Are you looking for contributors? Would love to learn more about this, it seems very interesting. I've been using React professionally for several years and following the react-three-fiber project for some time now.

I wasn't sure how to reach you but figured this may find you.

**Comment by satansdeer** [comment]
Hey @mmnavarr didn't see the question for too long. This was a small test project to see how does react-thee-fiber work. I wasn't looking for contributors, but the idea of continuing this project seems interesting to me. If you are still interested we can discuss it in my discord https://discord.gg/KPh8Vvb
